### PR TITLE
Allow reading and writing to IO::Handle (and derived) objects

### PR DESCRIPTION
**Pull request by lameventanas**
I was surprised that YAML::LoadFile() and YAML::DumpFile() didn't work on IO::Handle objects.

This fixes it for me.

### CODE REVIEW

**Comment by karenetheridge** [comment]
Cool!

I think it would be helpful to verify the use of IO::Handle in a test, to ensure that this doesn't regress in the future.

**Comment by lameventanas** [comment]
@karenetheridge 
Good idea, I added a test for IO::Pipe and IO::File.
But I'm not sure if IO::Pipe works in all platforms, maybe this test has to be skipped on Windows, any advise?

**Comment by karenetheridge** [comment]
I'd release as -TRIAL first to see how the various architectures handle it, and give it at least a week before releasing as stable.

**Comment by perlpunk** [comment]
merged, developer release 1.20_001
thanks!

**Pull request closed without merging**
